// Code generated by ormc; DO NOT EDIT.
// NOTE: Schema() and Values() must always be in the same field order.
// String PK: set via github.com/tinywasm/unixid before calling db.Create().
package skill

import (
	"github.com/tinywasm/orm"
)

func (m *cat) Schema() []orm.Field {
	return []orm.Field{
		{Name: "id", Type: orm.TypeInt64, Constraints: orm.ConstraintPK | orm.ConstraintAutoIncrement},
		{Name: "name", Type: orm.TypeText, Constraints: orm.ConstraintUnique},
	}
}

func (m *cat) Values() []any {
	return []any{
		m.ID,
		m.Name,
	}
}

func (m *cat) Pointers() []any {
	return []any{
		&m.ID,
		&m.Name,
	}
}

var catMeta = struct {
	TableName string
	ID string
	Name string
}{
	TableName: "cats",
	ID: "id",
	Name: "name",
}

func ReadOnecat(qb *orm.QB, model *cat) (*cat, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllcat(qb *orm.QB) ([]*cat, error) {
	var results []*cat
	err := qb.ReadAll(
		func() orm.Model { return &cat{} },
		func(m orm.Model) { results = append(results, m.(*cat)) },
	)
	return results, err
}

func (m *skillModel) Schema() []orm.Field {
	return []orm.Field{
		{Name: "id", Type: orm.TypeInt64, Constraints: orm.ConstraintPK | orm.ConstraintAutoIncrement},
		{Name: "cat_id", Type: orm.TypeInt64, Constraints: orm.ConstraintNone, Ref: "cats"},
		{Name: "name", Type: orm.TypeText, Constraints: orm.ConstraintUnique},
		{Name: "info", Type: orm.TypeText, Constraints: orm.ConstraintNone},
	}
}

func (m *skillModel) Values() []any {
	return []any{
		m.ID,
		m.CatID,
		m.Name,
		m.Info,
	}
}

func (m *skillModel) Pointers() []any {
	return []any{
		&m.ID,
		&m.CatID,
		&m.Name,
		&m.Info,
	}
}

var skillModelMeta = struct {
	TableName string
	ID string
	CatID string
	Name string
	Info string
}{
	TableName: "skills",
	ID: "id",
	CatID: "cat_id",
	Name: "name",
	Info: "info",
}

func ReadOneskillModel(qb *orm.QB, model *skillModel) (*skillModel, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllskillModel(qb *orm.QB) ([]*skillModel, error) {
	var results []*skillModel
	err := qb.ReadAll(
		func() orm.Model { return &skillModel{} },
		func(m orm.Model) { results = append(results, m.(*skillModel)) },
	)
	return results, err
}

func (m *paramModel) Schema() []orm.Field {
	return []orm.Field{
		{Name: "id", Type: orm.TypeInt64, Constraints: orm.ConstraintPK | orm.ConstraintAutoIncrement},
		{Name: "skill_id", Type: orm.TypeInt64, Constraints: orm.ConstraintNone, Ref: "skills"},
		{Name: "name", Type: orm.TypeText, Constraints: orm.ConstraintNone},
		{Name: "type", Type: orm.TypeText, Constraints: orm.ConstraintNone},
		{Name: "info", Type: orm.TypeText, Constraints: orm.ConstraintNone},
		{Name: "req", Type: orm.TypeBool, Constraints: orm.ConstraintNone},
	}
}

func (m *paramModel) Values() []any {
	return []any{
		m.ID,
		m.SkillID,
		m.Name,
		m.Type,
		m.Info,
		m.Req,
	}
}

func (m *paramModel) Pointers() []any {
	return []any{
		&m.ID,
		&m.SkillID,
		&m.Name,
		&m.Type,
		&m.Info,
		&m.Req,
	}
}

var paramModelMeta = struct {
	TableName string
	ID string
	SkillID string
	Name string
	Type string
	Info string
	Req string
}{
	TableName: "params",
	ID: "id",
	SkillID: "skill_id",
	Name: "name",
	Type: "type",
	Info: "info",
	Req: "req",
}

func ReadOneparamModel(qb *orm.QB, model *paramModel) (*paramModel, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllparamModel(qb *orm.QB) ([]*paramModel, error) {
	var results []*paramModel
	err := qb.ReadAll(
		func() orm.Model { return &paramModel{} },
		func(m orm.Model) { results = append(results, m.(*paramModel)) },
	)
	return results, err
}
